name: Release Please

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Type of release (patch, minor, major)'
        required: false
        default: 'auto'
        type: choice
        options:
          - auto
          - patch
          - minor
          - major

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          
      # Optional: Build and test before release
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: '18'
          cache: 'npm'
          
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
        
      - run: npm run type-check
        if: ${{ steps.release.outputs.release_created }}
        
      - run: npm run lint
        if: ${{ steps.release.outputs.release_created }}
        
      - run: npm run test:run
        if: ${{ steps.release.outputs.release_created }}