name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: salacia
          
      # Optional: Build and test before release
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        
      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: '18'
          cache: 'npm'
          
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
        
      - run: npm run type-check
        if: ${{ steps.release.outputs.release_created }}
        
      - run: npm run lint
        if: ${{ steps.release.outputs.release_created }}
        
      - run: npm run test:run
        if: ${{ steps.release.outputs.release_created }}